### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mnrusimh** [endrebak/epic#42]
I installed epic ver. 0.1.18 and no issues were reported. However, when I try running it on any dataset including the example dataset shipped with the software, I am getting the following error.

mnrusimh@bioserv:/nfs/analysis/epic$ epic --treatment test.bed --control control.bed
\# epic --treatment test.bed --control control.bed
\# epic --treatment test.bed --control control.bed # epic_version: 0.1.18, pandas_version: 0.12.0 (File: epic, Log level: INFO, Time: Tue, 04 Oct 2016 09:45:41 )
Traceback (most recent call last):
  File "/home/mnrusimh/Applications/epic/bin/epic", line 5, in <module>
    pkg_resources.run_script('bioepic==0.1.18', 'epic')
  File "/nfs/bio/sw/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/nfs/bio/sw/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/mnrusimh/Applications/epic/lib/python2.7/site-packages/bioepic-0.1.18-py2.7.egg/EGG-INFO/scripts/epic", line 193, in <module>
    estimated_readlength = find_readlength(args)
  File "/home/mnrusimh/Applications/epic/lib/python2.7/site-packages/bioepic-0.1.18-py2.7.egg/epic/utils/find_readlength.py", line 36, in find_readlength
    names=["Start", "End"])
  File "/nfs/bio/sw/lib/python2.7/site-packages/pandas-0.12.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 400, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/nfs/bio/sw/lib/python2.7/site-packages/pandas-0.12.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 205, in _read
    return parser.read()
  File "/nfs/bio/sw/lib/python2.7/site-packages/pandas-0.12.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 608, in read
    ret = self._engine.read(nrows)
  File "/nfs/bio/sw/lib/python2.7/site-packages/pandas-0.12.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 1028, in read
    data = self._reader.read(nrows)
  File "parser.pyx", line 706, in pandas.parser.TextReader.read (pandas/parser.c:6745)
  File "parser.pyx", line 728, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:6964)
  File "parser.pyx", line 804, in pandas.parser.TextReader._read_rows (pandas/parser.c:7780)
  File "parser.pyx", line 865, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:8512)
  File "parser.pyx", line 1105, in pandas.parser.TextReader._get_column_name (pandas/parser.c:11684)
IndexError: list index out of range

**Comment by endrebak** [comment]
Your pandas version is ancient. I guess I should throw an error if it is
too old. Thanks for reporting.

Fix it by running

pip install pandas==0.18.1
