### ISSUE TITLE
Error calculating readlength

### ISSUE THREAD

**Issue by abalter** [endrebak/epic#43]
I'm getting

```
# epic -t chip_A-sortsam.bam -c input_A-sortsam.bam -fs 300 (File: epic, Log level: INFO, Time: Thu, 06 Oct 2016 06:56:24 )
cat: write error: Broken pipe
Used first 10000 reads of chip_A-sortsam.bam to estimate a median read length of nan
Mean readlength: nan, max readlength: nan, min readlength: nan. (File: find_readlength, Log level: INFO, Time: Thu, 06 Oct 2016 06:56:25 )
# epic -t chip_A-sortsam.bam -c input_A-sortsam.bam -fs 300
Traceback (most recent call last):
  File "/home/users/balter/miniconda2/bin/epic", line 4, in <module>
    __import__('pkg_resources').run_script('bioepic==0.1.17', 'epic')
  File "/home/users/balter/miniconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/home/users/balter/miniconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/home/users/balter/miniconda2/lib/python2.7/site-packages/bioepic-0.1.17-py2.7.egg-info/scripts/epic", line 190, in <module>
    closest_readlength = get_closest_readlength(estimated_readlength)
  File "/home/users/balter/miniconda2/lib/python2.7/site-packages/epic/utils/find_readlength.py", line 63, in get_closest_readlength
    if d == min_difference][0]
IndexError: list index out of range
```

BAM files:

```
ls -l
total 6622033
-rw-rw-r-- 1 balter CompBio 3387571391 Oct  6 05:59 chip_A-sortsam.bam
-rw-rw-r-- 1 balter CompBio 3387571391 Oct  6 06:34 input_A-sortsam.bam
```

**Comment by abalter** [comment]
Uh, epic wants BEDs not BAMs. Closing. But for heaven's sake, allow bam inputs and convert them on the fly. Aligners spit out bams.

**Comment by endrebak** [comment]
Rude. Blocking.

**Comment by endrebak** [comment]
https://github.com/endrebak/epic/issues/44
