### ISSUE TITLE
bioepic: OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by anishdattani** [endrebak/epic#45]

**Comment by anishdattani** [comment]
I have installed bioepic and have run the epic program from the bin folder. However, each time I run my H3K27me3 ChIP against Input I get the following error: 

Merging the bins on both strands per chromosome. (File: count_reads_in_windows, Log level: INFO, Time: Thu, 03 Nov 2016 21:53:12 )
Merging ChIP and Input data. (File: helper_functions, Log level: INFO, Time: Thu, 03 Nov 2016 21:57:15 )
600000000.0 effective_genome_size (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
200 window size (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
0 total chip count (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
0.0 average_window_readcount (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
1 island_enriched_threshold (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
4.0 gap_contribution (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
1.0 boundary_contribution (File: compute_background_probabilites, Log level: DEBUG, Time: Thu, 03 Nov 2016 21:58:51 )
/home/anish/.local/lib/python2.7/site-packages/epic/statistics/compute_score_threshold.py:22: RuntimeWarning: divide by zero encountered in log
  score = -log(required_p_value)
Traceback (most recent call last):
  File "./epic", line 218, in <module>
    run_epic(args)
  File "/home/anish/.local/lib/python2.7/site-packages/epic/run/run_epic.py", line 47, in run_epic
    compute_background_probabilities(nb_chip_reads, args)
  File "/home/anish/.local/lib/python2.7/site-packages/epic/statistics/compute_background_probabilites.py", line 49, in compute_background_probabilities
    boundary_contribution, genome_length_in_bins)
  File "/home/anish/.local/lib/python2.7/site-packages/epic/statistics/compute_score_threshold.py", line 24, in compute_score_threshold
    current_scaled_score = int(round(score / BIN_SIZE))
OverflowError: cannot convert float infinity to integer


What does this mean? I know that there should be broad peaks as I find them running MACS2 broad-peak (no-model) option.  Forgive me - I am new to these sorts of analyses. 

Best, 
Anish

**Comment by endrebak** [comment]
Thanks for reporting. It seems like `epic` cannot interpret your files. What do they look like?

Please post the output of 

```
head <yourfiles> | cat -et
```

to this thread.

**Comment by anishdattani** [comment]
Hi, 

Sorry for the late reply. The following was what I inputted into epic: 

./epic --control /pathtofolder/lib.filtered.input.sorted_2_MARKDUP.bed --treatment /pathtofolder/lib.filtered.H3K27me3_2_new.sorted.MARKDUP.bed --number-cores 30 --fragment-size 300 --chromsizes /pathtofolder/Asxl.size.file --effective_genome_size 6e8 > /pathtohomefolder/h3k27.broad.csv 

My input folder looks like this: 

scaffold4^I1^I160^INB501801:1:HN3WLBGXY:4:11601:9830:10032^I159$
scaffold4^I1^I164^INB501801:1:HN3WLBGXY:3:13412:18598:13811^I163$
scaffold4^I1^I167^INB501801:1:HN3WLBGXY:3:22404:14294:20264^I166$
scaffold4^I15^I189^INB501801:1:HN3WLBGXY:2:23204:7996:11409^I174$
scaffold4^I1^I201^INB501801:1:HN3WLBGXY:3:21609:2881:5564^I200$
scaffold4^I46^I230^INB501801:1:HN3WLBGXY:4:23510:23247:4818^I184$
scaffold4^I67^I239^INB501801:1:HN3WLBGXY:4:11406:17309:7190^I172$
scaffold4^I80^I273^INB501801:1:HN3WLBGXY:4:21606:9304:15988^I193$
scaffold4^I76^I287^INB501801:1:HN3WLBGXY:1:22103:20705:12481^I211$
scaffold4^I95^I288^INB501801:1:HN3WLBGXY:3:23411:2064:14725^I193$


My treatment folder looks like this: 

scaffold4^I1^I164^INB501801:1:HN3WLBGXY:3:13412:18598:13811^I163$
scaffold4^I1^I165^INB501801:1:HN3WLBGXY:4:12512:24813:1400^I164$
scaffold4^I9^I188^INB501801:1:HN3WLBGXY:3:23511:22654:9868^I179$
scaffold4^I15^I189^INB501801:1:HN3WLBGXY:2:23204:7996:11409^I174$
scaffold4^I1^I204^INB501801:1:HN3WLBGXY:4:21412:4710:15556^I203$
scaffold4^I55^I239^INB501801:1:HN3WLBGXY:4:11508:23962:14301^I184$
scaffold4^I42^I250^INB501801:1:HN3WLBGXY:3:21401:2738:10832^I208$
scaffold4^I76^I287^INB501801:1:HN3WLBGXY:1:22103:20705:12481^I211$
scaffold4^I91^I298^INB501801:1:HN3WLBGXY:3:12411:9664:14867^I207$
scaffold4^I87^I304^INB501801:1:HN3WLBGXY:2:21106:6046:15213^I217$ 

My chromsize folder: 

scaffold4^I49623$
scaffold1^I75538$
scaffold2^I35872$
scaffold6^I61357$
scaffold3^I23435$
scaffold7^I107993$
scaffold10^I43946$
scaffold11^I23991$
scaffold8^I118074$
scaffold13^I28105$ 


I hope this helps. Thank you in advance. 

Best,  
Anish

**Comment by endrebak** [comment]
Effective genome size should be a number between 0 and 1.

You have no strand info in your files.
